version: '3.8'

services:
  shop_api:
    build:
      context: ..  # Указываем на директорию выше, то есть корень проекта
      dockerfile: lecture_2/hw/Dockerfile  # Путь к Dockerfile от корня проекта
    ports:
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
